### ISSUE TITLE
TypeError: Cannot set property 'defaultViewport' of undefined

### ISSUE THREAD

**Issue by lifeofmle** [gidztech/jest-puppeteer-docker#19]
I am using v1.1.2

I am trying to setup the testing framework but I get the following error with my `jest-puppeteer.config.js`

```
TypeError: Cannot set property 'defaultViewport' of undefined
```

Here is my config
```
const getConfig = require("jest-puppeteer-docker/lib/config");
 
const baseConfig = getConfig();
const customConfig = Object.assign({}, baseConfig);
 
customConfig.connect.defaultViewport = {
    width: 500,
    height: 500
};

customConfig.chromiumFlags = ["–ignore-certificate-errors"];
 
module.exports = customConfig;
```

I tried to do this to get around the error but got pass this initial error but got a new one
```
if (!(customConfig.connect)){
  customConfig.connect = {};
}
 
customConfig.connect.defaultViewport = {
    width: 500,
    height: 500
}; 
```
The new error is 
```
Docker Chromium: Attempt #2
Docker Chromium: Connected to WebSocket URL: ws://localhost:9222/devtools/browser/6c590786-e543-44f8-9975-845c7824bf5a
TypeError: Cannot read property 'watch' of undefined
    at setup (<dir>/node_modules/jest-environment-puppeteer/lib/global.js:30:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by gidztech** [comment]
Thanks for reporting this. I'm still trying to work out what caused this issue, but I think it's a change that has happened in one of the dependencies. I'll look in more detail tomorrow.

**Comment by gidztech** [comment]
I've got to the bottom of it now. The first problem was caused by not making sure that the `wsEndpoint` file existed. I'm not sure why it used to work though, but that's been fixed now.

The second problem was caused by a change in `jest-puppeteer`, which now requires a later version of Jest. If you update to 23.6.0 or above, the second error should go away. See https://github.com/smooth-code/jest-puppeteer/issues/195

I've published my fix with verson 1.1.3. Let me know if that fixes the issue for you.

**Comment by lifeofmle** [comment]
Thank you @gidztech your fix helped with the first issue. I am still getting the second error even with `jest: 23.6.0`. I created an example with CRA to illustrate the error. https://github.com/lifeofmle/diff

I will keep debugging on my side.

**Comment by gidztech** [comment]
In your global setup and teardown functions, you need to pass the `jestConfig` object through to `jest-puppeteer`. One of the changes they made in `jest-puppeteer`.

See https://github.com/gidztech/jest-puppeteer-docker#advanced-config

**Comment by lifeofmle** [comment]
Thank you so much for pointing that out for me. Let me know if there is any way to donate or contribute with any work that might help you.
